spring:
  application:
    name: hw11
    version: 1.0
  webflux:
    base-path: /api
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    user: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8080
