spring:
  application:
    name: hw05
    version: 1.0
  datasource:
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  shell:
    interactive:
      enabled: true
